### ISSUE TITLE
Mnemonic._entropy2mnemonic question

### ISSUE THREAD

**Issue by fanatid** [decred/bitcore-mnemonic#3]
https://github.com/decred/bitcore-mnemonic/blob/f211a23b535252616e7b19b7cc07f0b952c4e159/lib/mnemonic.js#L249-L264
only first 512 words from wordlist will be used, why this was done?

**Comment by jrick** [comment]
We use the [PGP word list](https://en.wikipedia.org/wiki/PGP_word_list) and not BIP0039.  In the PGP word list, there are 512 words total split into two lists of 256 words each.  It alternates through each list for even and odd indexes.
